# Generated by Django 3.1.3 on 2020-12-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
            ],
            options={
                'db_table': 'cafes',
            },
        ),
        migrations.CreateModel(
            name='ConvenientStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
            ],
            options={
                'db_table': 'convenient_stores',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('line', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
            ],
            options={
                'db_table': 'subways',
            },
        ),
    ]
