# Generated by Django 3.1.3 on 2020-12-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20201202_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'school_grades',
            },
        ),
        migrations.CreateModel(
            name='SubwayLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'subway_lines',
            },
        ),
        migrations.RemoveField(
            model_name='school',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subway',
            name='line',
        ),
        migrations.AddField(
            model_name='cafe',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convenientstore',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.schoolgrade'),
        ),
        migrations.AddField(
            model_name='subway',
            name='subway_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.subwayline'),
        ),
    ]
