# Generated by Django 3.1.3 on 2020-12-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('top_floor', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('trade_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'apartments',
            },
        ),
        migrations.CreateModel(
            name='ApartmentComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('household_number', models.IntegerField()),
                ('completion_year', models.CharField(max_length=20)),
                ('image_url', models.URLField(max_length=1000, null=True)),
                ('address', models.CharField(max_length=1000)),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
            ],
            options={
                'db_table': 'complexes',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'neighborhoods',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'trade_types',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.neighborhood')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='ApartmentSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.size')),
            ],
            options={
                'db_table': 'apartments_sizes',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmentcomplex'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.district'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='size',
            field=models.ManyToManyField(through='apartment.ApartmentSize', to='apartment.Size'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='trade_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.tradetype'),
        ),
    ]
