# Generated by Django 3.1.3 on 2020-12-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
