# Generated by Django 3.1.3 on 2020-12-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20201202_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='trade_date',
        ),
        migrations.AddField(
            model_name='apartment',
            name='trade_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='trade_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='size',
        ),
        migrations.AddField(
            model_name='apartment',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.size'),
        ),
        migrations.DeleteModel(
            name='ApartmentSize',
        ),
    ]
