# Generated by Django 3.1.3 on 2020-12-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_auto_20201204_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
