# Generated by Django 3.1.3 on 2020-12-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_auto_20201207_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='district',
        ),
        migrations.RemoveField(
            model_name='district',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='apartment',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.neighborhood'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.district'),
        ),
    ]
