# Generated by Django 3.1.3 on 2020-12-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20, null=True)),
                ('image_url', models.URLField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'agencies',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'directions',
            },
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_elevator', models.BooleanField()),
            ],
            options={
                'db_table': 'elevators',
            },
        ),
        migrations.CreateModel(
            name='FloorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'floor_types',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'parkings',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'structure_types',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('register_number', models.IntegerField()),
                ('area', models.IntegerField()),
                ('completion_year', models.CharField(max_length=20)),
                ('deposit', models.IntegerField()),
                ('rent', models.IntegerField(null=True)),
                ('maintenance_cost', models.IntegerField(null=True)),
                ('top_floor', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('address', models.CharField(max_length=1000)),
                ('available_date', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.agency')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.direction')),
                ('elevator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.elevator')),
                ('floor_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.floortype')),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.parking')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomtype')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.status')),
                ('structure_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.structuretype')),
                ('trade_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.tradetype')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
