# Generated by Django 3.1.3 on 2020-12-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='elevator',
        ),
        migrations.AddField(
            model_name='room',
            name='has_elevator',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='deposit',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Elevator',
        ),
    ]
